import type { TestMethod } from "../../types";

export const WORKING_METHODS: TestMethod[] = [
  {
    id: "m1",
    name: "EN ISO 2411: 2000 Adhesion of Rubber- or Plastic-Coated...",
    equipment: "UTM/MTM",
    lastModified: "2/8/2017 3:20:56 AM",
    methodType: "Designed for 180° Peel testing...",
    notes: "",
    inUse: true,
  },
  {
    id: "m2",
    name: "Generic 180° Peel",
    equipment: "UTM/MTM",
    lastModified: "5/24/2016 2:24:36 PM",
    methodType: "Designed for 180° Peel testing...",
    notes: "",
    inUse: true,
  },
  {
    id: "m3",
    name: "Generic 7 Strand",
    equipment: "UTM/MTM & Strain Extensometer",
    lastModified: "9/9/2013 10:36:41 AM",
    methodType: "Designed for testing 7 Strand...",
    notes: "",
  },
  {
    id: "m4",
    name: "Generic 7 Strand - Continue Strain From Position",
    equipment: "UTM/MTM & Strain Extensometer",
    lastModified: "3/10/2015 12:08:07 PM",
    methodType: "Designed for testing 7 Strand...",
    notes: "",
  },
  {
    id: "m5",
    name: "Generic Sheet Hardness",
    equipment: "UTM/MTM with Brinell Hardness",
    lastModified: "6/30/2016 7:58:16 AM",
    methodType: "Designed for testing with a UTM...",
    notes: "",
  },
  {
    id: "m6",
    name: "Generic Climbing Drum Peel",
    equipment: "UTM/MTM",
    lastModified: "1/20/2012 3:16:34 PM",
    methodType: "Designed for Climbing Drum Peel",
    notes: "",
  },
  {
    id: "m7",
    name: "Generic Compression - Force vs. Position",
    equipment: "UTM/MTM",
    lastModified: "10/23/2024 9:55:06 AM",
    methodType: "Designed for Compression...",
    notes: "",
  },
  {
    id: "m8",
    name: "Generic Compression - Force vs. Position using SlopeChange",
    equipment: "UTM/MTM",
    lastModified: "7/20/2023 9:11:39 AM",
    methodType: "Designed for Compression...",
    notes: "",
  },
  {
    id: "m9",
    name: "Generic Compression - Force vs. Time",
    equipment: "UTM/MTM",
    lastModified: "1/30/2015 10:47:50 AM",
    methodType: "Designed for Compression",
    notes: "",
  },
  {
    id: "m10",
    name: "Generic Compression - Set Initial Platen to Zero and Park...",
    equipment: "UTM/MTM",
    lastModified: "2/26/2015 11:35:09 AM",
    methodType: "A utility method to allow you to...",
    notes: "Used for methods that start from...",
  },
  {
    id: "m11",
    name: "Generic Compression - Stress vs. Strain (from Position)",
    equipment: "UTM/MTM",
    lastModified: "1/20/2012 3:16:53 PM",
    methodType: "Designed for Compression...",
    notes: "",
  },
  {
    id: "m12",
    name: "Generic Compression Cycle",
    equipment: "UTM/MTM",
    lastModified: "1/18/2012 4:29:06 PM",
    methodType: "Designed for Compression...",
    notes: "",
  },
  {
    id: "m13",
    name: "Generic Compression of Foam for Automotive Parts",
    equipment: "UTM/MTM",
    lastModified: "1/18/2012 4:29:17 PM",
    methodType: "Designed for Compression...",
    notes: "",
  },
  {
    id: "m14",
    name: "Generic Compression of Foam for Automotive Parts (until...)",
    equipment: "UTM/MTM",
    lastModified: "1/30/2015 1:42:09 PM",
    methodType: "Designed for Compression...",
    notes: "",
  },
  {
    id: "m15",
    name: "Generic Compression to Load - multicycle",
    equipment: "UTM/MTM",
    lastModified: "10/9/2015 2:16:08 PM",
    methodType: "Load cycling - variable mid-...",
    notes: "",
  },
  {
    id: "m16",
    name: "Generic Compression with Deflectometer",
    equipment: "UTM/MTM & Deflectometer",
    lastModified: "1/30/2015 10:48:12 AM",
    methodType: "Designed for Compression...",
    notes: "",
  },
  {
    id: "m17",
    name: "Generic Compression with Deflectometer - Force vs. Deflection",
    equipment: "UTM/MTM & Deflectometer",
    lastModified: "7/31/2023 12:57:01 PM",
    methodType: "Designed for Compression...",
    notes: "",
  },
  {
    id: "m18",
    name: "Generic Compression with Deflectometer using Vector Video Extensometer",
    equipment: "UTM/MTM & Deflectometer",
    lastModified: "10/9/2015 2:16:08 PM",
    methodType: "Designed for Compression...",
    notes: "",
  },
];

export const STANDARD_METHODS: TestMethod[] = WORKING_METHODS.slice(0, 6);